<?xml version="1.0" encoding="UTF-8"?>
<alr:test-suite xmlns:alr="urn:model.allure.qatools.yandex.ru" start="1729890332697" stop="1729890332706" version="1.4.0">
  <name>Magento\Indexer\Test\Unit\App\IndexerTest</name>
  <test-cases>
    <test-case start="1729890332698" stop="1729890332701" status="passed">
      <name>testExecute with data set "set1"</name>
    </test-case>
    <test-case start="1729890332701" stop="1729890332703" status="passed">
      <name>testExecute with data set "set2"</name>
    </test-case>
    <test-case start="1729890332703" stop="1729890332706" status="passed">
      <name>testCatchException</name>
    </test-case>
  </test-cases>
</alr:test-suite>
