<?xml version="1.0" encoding="UTF-8"?>
<alr:test-suite xmlns:alr="urn:model.allure.qatools.yandex.ru" start="1729890261876" stop="1729890261887" version="1.4.0">
  <name>Magento\Analytics\Test\Unit\Controller\Adminhtml\Subscription\RetryTest</name>
  <test-cases>
    <test-case start="1729890261876" stop="1729890261881" status="passed">
      <name>testExecute</name>
    </test-case>
    <test-case start="1729890261882" stop="1729890261884" status="passed">
      <name>testExecuteWithException with data set #0</name>
    </test-case>
    <test-case start="1729890261884" stop="1729890261886" status="passed">
      <name>testExecuteWithException with data set #1</name>
    </test-case>
  </test-cases>
</alr:test-suite>
