<?xml version="1.0" encoding="UTF-8"?>
<alr:test-suite xmlns:alr="urn:model.allure.qatools.yandex.ru" start="1729890388744" stop="1729890388797" version="1.4.0">
  <name>Magento\Sales\Test\Unit\Model\RefundInvoiceTest</name>
  <test-cases>
    <test-case start="1729890388745" stop="1729890388762" status="passed">
      <name>testOrderCreditmemo with data set "TestWithNotifyTrue"</name>
    </test-case>
    <test-case start="1729890388763" stop="1729890388777" status="passed">
      <name>testOrderCreditmemo with data set "TestWithNotifyFalse"</name>
    </test-case>
    <test-case start="1729890388778" stop="1729890388787" status="passed">
      <name>testDocumentValidationException</name>
    </test-case>
    <test-case start="1729890388787" stop="1729890388796" status="passed">
      <name>testCouldNotCreditmemoException</name>
    </test-case>
  </test-cases>
</alr:test-suite>
